# Generated by Django 3.2.14 on 2022-07-11 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogblock',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_block', to='app.blog'),
        ),
        migrations.AlterField(
            model_name='caseblock',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_block', to='app.cases'),
        ),
        migrations.AlterField(
            model_name='clientblock',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_block', to='app.clients'),
        ),
        migrations.AlterField(
            model_name='companiesblock',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_block', to='app.companies'),
        ),
        migrations.AlterField(
            model_name='faqblock',
            name='faq',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faq_block', to='app.faq'),
        ),
        migrations.AlterField(
            model_name='industriesblock',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='industry_block', to='app.industries'),
        ),
        migrations.AlterField(
            model_name='menulink',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_link', to='app.menu'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_type', to='app.services'),
        ),
        migrations.AlterField(
            model_name='servicetypeblock',
            name='service_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_type_block', to='app.servicetype'),
        ),
        migrations.AlterField(
            model_name='whyusblock',
            name='why_us',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='why_us_block', to='app.whyus'),
        ),
    ]
