# Generated by Django 3.2.14 on 2022-07-12 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220711_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogblock',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block', to='app.blog'),
        ),
    ]
