# Generated by Django 3.2.14 on 2022-07-12 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_blogblock_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseblock',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block', to='app.cases'),
        ),
        migrations.AlterField(
            model_name='clientblock',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block', to='app.clients'),
        ),
        migrations.AlterField(
            model_name='companiesblock',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block', to='app.companies'),
        ),
        migrations.AlterField(
            model_name='faqblock',
            name='faq',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block', to='app.faq'),
        ),
        migrations.AlterField(
            model_name='industriesblock',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block', to='app.industries'),
        ),
        migrations.AlterField(
            model_name='menulink',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link', to='app.menu'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type', to='app.services'),
        ),
        migrations.AlterField(
            model_name='servicetypeblock',
            name='service_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block', to='app.servicetype'),
        ),
        migrations.AlterField(
            model_name='whyusblock',
            name='why_us',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block', to='app.whyus'),
        ),
    ]
