# Generated by Django 3.2.14 on 2022-07-12 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220712_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulink',
            name='menu',
            field=models.ForeignKey(default='Menu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link', to='app.menu'),
        ),
    ]
