# Generated by Django 3.2.14 on 2022-07-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220712_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseblock',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
