# Generated by Django 3.2.14 on 2022-07-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_caseblock_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogblock',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='clientblock',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='companiesblock',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='industriesblock',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='servicetypeblock',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
