# Generated by Django 3.2.14 on 2022-07-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20220713_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogblock',
            name='image',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='caseblock',
            name='image',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clientblock',
            name='image',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='companiesblock',
            name='image',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='industriesblock',
            name='image',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='servicetypeblock',
            name='image',
            field=models.IntegerField(null=True),
        ),
    ]
