# Generated by Django 3.2.14 on 2022-07-15 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220713_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companiesblock',
            name='description',
        ),
        migrations.AddField(
            model_name='blogblock',
            name='content',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='caseblock',
            name='content',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientblock',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companiesblock',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industriesblock',
            name='content',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicetypeblock',
            name='content',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicetypeblock',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='menulink',
            name='menu',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link', to='app.menu'),
        ),
    ]
