# Generated by Django 3.2.14 on 2022-07-15 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20220715_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whyusblock',
            name='why_us',
            field=models.ForeignKey(default='2', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block', to='app.whyus'),
        ),
    ]
