# Generated by Django 3.2.14 on 2022-07-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_whyusblock_why_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogblock',
            name='image',
            field=models.ImageField(null=True, upload_to='C:\\Users\\anton\\PycharmProjects\\django_cms\\project\\media'),
        ),
        migrations.AlterField(
            model_name='caseblock',
            name='image',
            field=models.ImageField(null=True, upload_to='C:\\Users\\anton\\PycharmProjects\\django_cms\\project\\media'),
        ),
        migrations.AlterField(
            model_name='clientblock',
            name='image',
            field=models.ImageField(null=True, upload_to='C:\\Users\\anton\\PycharmProjects\\django_cms\\project\\media'),
        ),
        migrations.AlterField(
            model_name='companiesblock',
            name='image',
            field=models.ImageField(null=True, upload_to='C:\\Users\\anton\\PycharmProjects\\django_cms\\project\\media'),
        ),
        migrations.AlterField(
            model_name='industriesblock',
            name='image',
            field=models.ImageField(null=True, upload_to='C:\\Users\\anton\\PycharmProjects\\django_cms\\project\\media'),
        ),
        migrations.AlterField(
            model_name='servicetypeblock',
            name='image',
            field=models.ImageField(null=True, upload_to='C:\\Users\\anton\\PycharmProjects\\django_cms\\project\\media'),
        ),
    ]
