# Generated by Django 3.2.14 on 2022-07-19 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20220718_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menusectionlinks',
            name='menu_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link', to='app.menuservicessections'),
        ),
        migrations.AlterField(
            model_name='menuservices',
            name='menu',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service', to='app.menu'),
        ),
        migrations.AlterField(
            model_name='menuservices',
            name='type',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='menuservices',
            name='value',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='menuservicessections',
            name='menu_services',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section', to='app.menuservices'),
        ),
    ]
