# Generated by Django 3.2.15 on 2022-09-13 07:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogblock',
            name='backgroundImage',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='caseblock',
            name='backgroundImage',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='back_image'),
        ),
    ]
