# Generated by Django 3.2.15 on 2022-09-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20220913_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogblock',
            name='pagination',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='caseblock',
            name='pagination',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='clientblock',
            name='pagination',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='companiesblock',
            name='pagination',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='faqblock',
            name='pagination',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='industriesblock',
            name='pagination',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='industrytype',
            name='pagination',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='pagination',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='servicetypeblock',
            name='pagination',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='whyusblock',
            name='pagination',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
